# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY next.config.js ./
COPY tsconfig.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Add build arguments
ARG AVAILABILITY_CALENDAR_BAY1_ID
ARG AVAILABILITY_CALENDAR_BAY2_ID
ARG AVAILABILITY_CALENDAR_BAY3_ID
ARG BOOKING_CALENDAR_BAY1_ID
ARG BOOKING_CALENDAR_BAY2_ID
ARG BOOKING_CALENDAR_BAY3_ID
ARG EMAIL_PASSWORD
ARG EMAIL_USER
ARG GCP_SA_KEY
ARG JWT_SECRET
ARG LINE_CLIENT_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GUEST_PASSWORD
ARG NEXT_PUBLIC_LINE_CLIENT_ID
ARG NEXT_PUBLIC_LINE_NOTIFY_TOKEN
ARG NEXT_PUBLIC_LINE_REDIRECT_URI
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NODE_ENV
ARG SERVICE_ACCOUNT_KEY_BASE64
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL

# Set environment variables
ENV AVAILABILITY_CALENDAR_BAY1_ID=$AVAILABILITY_CALENDAR_BAY1_ID
ENV AVAILABILITY_CALENDAR_BAY2_ID=$AVAILABILITY_CALENDAR_BAY2_ID
ENV AVAILABILITY_CALENDAR_BAY3_ID=$AVAILABILITY_CALENDAR_BAY3_ID
ENV BOOKING_CALENDAR_BAY1_ID=$BOOKING_CALENDAR_BAY1_ID
ENV BOOKING_CALENDAR_BAY2_ID=$BOOKING_CALENDAR_BAY2_ID
ENV BOOKING_CALENDAR_BAY3_ID=$BOOKING_CALENDAR_BAY3_ID
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV EMAIL_USER=$EMAIL_USER
ENV GCP_SA_KEY=$GCP_SA_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV LINE_CLIENT_SECRET=$LINE_CLIENT_SECRET
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_GUEST_PASSWORD=$NEXT_PUBLIC_GUEST_PASSWORD
ENV NEXT_PUBLIC_LINE_CLIENT_ID=$NEXT_PUBLIC_LINE_CLIENT_ID
ENV NEXT_PUBLIC_LINE_NOTIFY_TOKEN=$NEXT_PUBLIC_LINE_NOTIFY_TOKEN
ENV NEXT_PUBLIC_LINE_REDIRECT_URI=$NEXT_PUBLIC_LINE_REDIRECT_URI
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NODE_ENV=$NODE_ENV
ENV SERVICE_ACCOUNT_KEY_BASE64=$SERVICE_ACCOUNT_KEY_BASE64
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL

# Build application
RUN npm run build

# Production stage
FROM node:18-alpine AS runner

WORKDIR /app

# Set production environment variables
ENV NODE_ENV=production
ENV PORT=8080

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Add build arguments for production stage
ARG AVAILABILITY_CALENDAR_BAY1_ID
ARG AVAILABILITY_CALENDAR_BAY2_ID
ARG AVAILABILITY_CALENDAR_BAY3_ID
ARG BOOKING_CALENDAR_BAY1_ID
ARG BOOKING_CALENDAR_BAY2_ID
ARG BOOKING_CALENDAR_BAY3_ID
ARG EMAIL_PASSWORD
ARG EMAIL_USER
ARG GCP_SA_KEY
ARG JWT_SECRET
ARG LINE_CLIENT_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GUEST_PASSWORD
ARG NEXT_PUBLIC_LINE_CLIENT_ID
ARG NEXT_PUBLIC_LINE_NOTIFY_TOKEN
ARG NEXT_PUBLIC_LINE_REDIRECT_URI
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG SERVICE_ACCOUNT_KEY_BASE64
ARG SUPABASE_SERVICE_ROLE_KEY
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL

# Set environment variables for production
ENV AVAILABILITY_CALENDAR_BAY1_ID=$AVAILABILITY_CALENDAR_BAY1_ID
ENV AVAILABILITY_CALENDAR_BAY2_ID=$AVAILABILITY_CALENDAR_BAY2_ID
ENV AVAILABILITY_CALENDAR_BAY3_ID=$AVAILABILITY_CALENDAR_BAY3_ID
ENV BOOKING_CALENDAR_BAY1_ID=$BOOKING_CALENDAR_BAY1_ID
ENV BOOKING_CALENDAR_BAY2_ID=$BOOKING_CALENDAR_BAY2_ID
ENV BOOKING_CALENDAR_BAY3_ID=$BOOKING_CALENDAR_BAY3_ID
ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV EMAIL_USER=$EMAIL_USER
ENV GCP_SA_KEY=$GCP_SA_KEY
ENV JWT_SECRET=$JWT_SECRET
ENV LINE_CLIENT_SECRET=$LINE_CLIENT_SECRET
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_GUEST_PASSWORD=$NEXT_PUBLIC_GUEST_PASSWORD
ENV NEXT_PUBLIC_LINE_CLIENT_ID=$NEXT_PUBLIC_LINE_CLIENT_ID
ENV NEXT_PUBLIC_LINE_NOTIFY_TOKEN=$NEXT_PUBLIC_LINE_NOTIFY_TOKEN
ENV NEXT_PUBLIC_LINE_REDIRECT_URI=$NEXT_PUBLIC_LINE_REDIRECT_URI
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV SERVICE_ACCOUNT_KEY_BASE64=$SERVICE_ACCOUNT_KEY_BASE64
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL

# Expose port
EXPOSE 8080

# Start the application
CMD ["node", "server.js"] 