/**
 * The staff booking notification, pinned byte for byte.
 *
 * This message used to be built inline inside
 * `app/api/notifications/line/route.ts`, reachable only by HTTP POSTing our own
 * serverless function. `lib/notifications/staffLine.ts` lifted it out so the
 * booking-create route can call it in process.
 *
 * The expected strings below were generated by running the PRE-extraction code
 * from git at the time of the move — they are not what the new implementation
 * happens to produce. Staff read these off their phones and act on the field
 * order, so a whitespace change here is a real change.
 */
import { buildBookingCreatedMessage } from '@/lib/notifications/staffLine';

// The builder logs its type-display branch; keep the suite output readable.
beforeAll(() => {
  jest.spyOn(console, 'log').mockImplementation(() => {});
});
afterAll(() => {
  jest.restoreAllMocks();
});

describe('buildBookingCreatedMessage', () => {
  it('renders a new customer on the normal bay rate', () => {
    expect(
      buildBookingCreatedMessage({
        channel: 'Website',
        standardizedData: {
          lineNotification: { bookingName: 'Somchai P.', customerLabel: 'Somchai Prasert' },
          bookingId: 'BK260731ABCD',
          customerName: 'Somchai Prasert',
          email: 'somchai@example.com',
          phoneNumber: '0812345678',
          date: '2026-08-03',
          formattedDate: 'Mon, 3rd August',
          startTime: '14:00',
          endTime: '15:00',
          bayName: 'Bay 2',
          duration: 1,
          numberOfPeople: 2,
        },
      })
    ).toBe(
      'Booking Notification (ID: BK260731ABCD)\n' +
        'Customer Name: New Customer\n' +
        'Booking Name: Somchai P.\n' +
        'Email: somchai@example.com\n' +
        'Phone: 0812345678\n' +
        'Date: Mon, 3rd August\n' +
        'Time: 14:00 - 15:00\n' +
        'Bay: Bay 2\n' +
        'Type: Normal Bay Rate\n' +
        'People: 2\n' +
        'Channel: Website\n' +
        '\n' +
        'This booking has been auto-confirmed. No need to re-confirm with the customer. Please double check bay selection'
    );
  });

  it('renders an existing customer on a simulator package, with notes', () => {
    expect(
      buildBookingCreatedMessage({
        customerCode: 'CUS-00123',
        packageInfo: 'Silver (15H)',
        bookingType: 'Package',
        packageName: 'Silver (15H)',
        customerNotes: 'Left-handed clubs please',
        channel: 'LINE',
        standardizedData: {
          lineNotification: { bookingName: 'Anna K.', customerLabel: 'Anna Kowalski' },
          bookingId: 'BK260731EFGH',
          customerName: 'Anna Kowalski',
          email: 'anna@example.com',
          phoneNumber: '0898765432',
          date: '2026-08-04',
          formattedDate: 'Tue, 4th August',
          startTime: '17:30',
          endTime: '19:30',
          bayName: 'Bay 4 (AI Lab)',
          duration: 2,
          numberOfPeople: 4,
          customerCode: 'CUS-00123',
        },
      })
    ).toBe(
      'Booking Notification (ID: BK260731EFGH)\n' +
        'Customer Name: Anna Kowalski\n' +
        'Booking Name: Anna K.\n' +
        'Email: anna@example.com\n' +
        'Phone: 0898765432\n' +
        'Date: Tue, 4th August\n' +
        'Time: 17:30 - 19:30\n' +
        'Bay: Bay 4 (AI Lab)\n' +
        'Type: Package (Silver (15H))\n' +
        'People: 4\n' +
        'Channel: LINE\n' +
        'Notes: Left-handed clubs please\n' +
        '\n' +
        'This booking has been auto-confirmed. No need to re-confirm with the customer. Please double check bay selection'
    );
  });

  /**
   * The legacy shape still matters: seven other callers POST the HTTP route
   * without `standardizedData`, and only that path runs `formatDateWithOrdinal`
   * on the raw date.
   */
  it('renders a legacy payload with no standardizedData, formatting the date itself', () => {
    expect(
      buildBookingCreatedMessage({
        customerCode: 'CUS-00999',
        customerName: 'Legacy Caller',
        bookingName: 'Legacy Caller',
        email: '',
        phoneNumber: '',
        bookingDate: '2026-08-21',
        bookingStartTime: '10:00',
        bookingEndTime: '12:00',
        bayNumber: 'Bay 1 (Bar)',
        duration: 2,
        numberOfPeople: 3,
        bookingType: 'Play_Food_Package',
        packageName: 'SET_B',
        bookingId: 'BK260731IJKL',
      })
    ).toBe(
      'Booking Notification (ID: BK260731IJKL)\n' +
        'Customer Name: Legacy Caller\n' +
        'Booking Name: Legacy Caller\n' +
        'Email: Not provided\n' +
        'Phone: Not provided\n' +
        'Date: Fri, 21st August\n' +
        'Time: 10:00 - 12:00\n' +
        'Bay: Bay 1 (Bar)\n' +
        'Type: Play & Food Package (SET_B)\n' +
        'People: 3\n' +
        'Channel: Website\n' +
        '\n' +
        'This booking has been auto-confirmed. No need to re-confirm with the customer. Please double check bay selection'
    );
  });

  /**
   * A booking with no `customerCode` is a first-timer, and staff are told so
   * rather than being shown a name the CRM has not matched yet.
   */
  it('labels a booking with no customer code as a new customer', () => {
    const msg = buildBookingCreatedMessage({
      customerName: 'Should Not Appear',
      bookingName: 'Walk In',
      bookingDate: '2026-08-21',
    });
    expect(msg).toContain('Customer Name: New Customer');
    expect(msg).not.toContain('Should Not Appear');
  });
});
