name: Daily Database Sync

on:
  schedule:
    # Run at 2:00 AM UTC (9:00 AM Thailand time)
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  run-sync-scripts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install additional dependencies
        run: npm install natural
        
      - name: Run customer matching sync
        run: node scripts/sync-customer-matching.js --all
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_CRM_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_CRM_SUPABASE_URL }}
          NEXT_PUBLIC_CRM_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_CRM_SUPABASE_KEY }}
          CONFIDENCE_THRESHOLD: 0.85
          DEBUG_MODE: 'false'
          
      - name: Run packages sync
        run: node scripts/sync-packages.js --all
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_CRM_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_CRM_SUPABASE_URL }}
          NEXT_PUBLIC_CRM_SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_CRM_SUPABASE_KEY }}
          DEBUG_MODE: 'false'
          
      - name: Log completion
        run: echo "Sync process completed at $(date)"
